### ISSUE TITLE
2x unmotivated in the emotions

### ISSUE THREAD

**Issue by Robin-Sch** [mrzmyr/pixy-mood-tracker-app#124]
On the emotion picker tab and then the more tab, there is 2x "unmotivated".

1x in the light yellow category
1x in the light green category

The one in the light green category is linked with "motivated" (selecting that "unmotivated" or the "motivated" automatically selects the other too).

On the show less tab, there is 1x "unmotivated" (and not "motivated"), but it's in the wrong (green) category.

Besides that, I think that "hyper", "thankful" and "surprised" (grey category) are placed in the wrong category, because they are positive aren't they? And most others (except maybe "meh" and "bored") in the grey category I would mark light yellow instead of grey, but yeah that's just my opinion.

Maybe it would be possible to customize in which category they belong via the app, because some people experience for example "overwhelmed" (more) negative than others do.

~~Also, is it possible to opt out of the behavioral data?~~
Maybe you could explain what "behavioral data" means with the toggler in the data settings tab, or move it to the privacy tab.

**Comment by Robin-Sch** [comment]
Also, if you answer postive (green) to how was your day, maybe you could move the negative ones under a collapse or something, to avoid having so many to pick from. Same with a negative day.

Or manually be able to add/remove an emotion.

**Comment by mrzmyr** [comment]
Hi @Robin-Sch, thanks for your in-depth feedback.

**_> On the emotion picker tab and then the more tab, there is 2x "unmotivated"._**

This has been fixed in df72ed6294468e8d7f5c200a5cc1bd92fbf3561f and is live with versions >= 1.7.1. What version are you on?

**_> Besides that, I think that "hyper", "thankful" and "surprised" (grey category) are placed in the wrong category, because they are positive aren't they? And most others (except maybe "meh" and "bored") in the grey category I would mark light yellow instead of grey, but yeah that's just my opinion._**

You're pointing out a very important, but also a difficult topic here: [Emotion classification](https://en.wikipedia.org/wiki/Emotion_classification#Lists_of_emotions). From my fair bit of research, emotion classification is as complex as the human itself. Therefore, I aligned the feelings listed mostly around the research from [Yale Center for Emotional Intelligence (YCEI)](https://medicine.yale.edu/childstudy/services/community-and-schools-programs/center-for-emotional-intelligence/) and the [How We Feel App](https://howwefeel.org).
From my point of view, "hyper",  "thankful" and "surprised" can be positive as well as negative, therefore I kept them in the neutral category (see next section on "why?")

**_> Maybe it would be possible to customize in which category they belong via the app, because some people experience for example "overwhelmed" (more) negative than others do._**

Keeping emotions in the neutral category when it's not 100% clear if they're positive or negative, makes it possible for the user to judge on their own. I think it's the best way to do so without adding additional complexity to the app interface. Let me know if you have a different idea on this.

**_> Maybe you could explain what "behavioral data" means with the toggler in the data settings tab, or move it to the privacy tab._**

Good point, just moved it. (fa5c4fd89b8a8789b89c1cb7e2b70690c393cafa)

_**Also, if you answer postive (green) to how was your day, maybe you could move the negative ones under a collapse or something, to avoid having so many to pick from. Same with a negative day.**_

Totally agree, this is already the case if you open the "More +" view (if a negative mood it selected, it scrolls to the left).
I submitted it to the [feature voting board here](https://pixy.hellonext.co/p/scroll-to-emotion-category).

**Comment by Robin-Sch** [comment]
> This has been fixed in https://github.com/mrzmyr/pixy-mood-tracker-app/commit/df72ed6294468e8d7f5c200a5cc1bd92fbf3561f and is live with versions >= 1.7.1. What version are you on?

I downloaded the app earlier today, I'm on v1.68.0 (ig 1.6.8 then?). The latest update was on 24 dec 2022 according to the google play store. Maybe this is because you made a typo and released version 1.68.0 instead of 1.6.8, and 1.68 > 1.7.1, so it doesn't update it?

> Keeping emotions in the neutral category when it's not 100% clear if they're positive or negative, makes it possible for the user to judge on their own. I think it's the best way to do so without adding additional complexity to the app interface. Let me know if you have a different idea on this.

Well I think that users should be able to change (edit, add and remove) emotions and group them by themselves. This way they all can judge themselves, and also remove emotions they won't ever use. Just like with the tag system, but then also with categories. It would add a lot of complexity to the app, but in my eyes, is the best thing to do.

**Comment by mrzmyr** [comment]
I use [Expo](https://expo.dev/) for app updates, which do not need to go through the Play Store. 

**How to update**
- Close the app
- Open it again (it fetches the latest app in the background)
- Wait 5 seconds (make sure the update it fetched completely)
- Close the app
- Open it again (old version is replaced with the new one)
- Check the version in the settings screen (the app should be updated)

(This is usually done over the days by the users and updates the app on the fly)

According to your idea about the emotions. I just added a [feature entry](https://pixy.hellonext.co/p/add-custom-emotions) to the feature board. Let's see what the others users vote on. 

Highly appreciate your feedback. Thank you.

**Comment by Robin-Sch** [comment]
Ah that would explain it, I've removed internet permission from the app, and so it isn't able to update on it's own.

And yeah, no need to thank me. Thank you for creating such a beautiful open source app.

**Comment by Robin-Sch** [comment]
Also, you _might_ be able to submit your app to f-droid, an open source app store for android. Check this: https://f-droid.org/docs/Inclusion_Policy/ (not sure if you meet every requirement).

If not, you might be able to submit it to IzzyOnDroid (https://gitlab.com/IzzyOnDroid/repo/#what-are-the-requirements-an-app-must-meet-to-be-included-with-the-repo) and still get it on f-droid that way (only users need to enable the IzzyOnDroid repo).

But yeah, seems like that would take a lot of time and work.

**Comment by mrzmyr** [comment]
I'm not aiming to submit this app to f-droid for now. 
And as Expo's auto-updates are used for Pixy it does not meet the requirements anyway. 

If you want to find a way to submit Pixy to f-droid, go ahead.
It will just not be officially supported by me.
